# Standalone Escalation Severity scorer for Problem 4 (Delinquency Escalation / Loss
# Severity). Generated by Notebook 28 -- loads severity_scoring_bundle.json (saved alongside this
# file) and scores one customer's real D_* engineered features into a severity tier + LGD.
# No training happens here; every weight/cutpoint/mean/std is frozen from Notebook 27's real run.
import json
import math
from pathlib import Path

BUNDLE_PATH = Path(__file__).parent / "severity_scoring_bundle.json"


def load_bundle(path=BUNDLE_PATH):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _is_missing(value):
    # None covers a plain missing key/explicit None; NaN (float('nan')) is how pandas/numpy
    # represent a missing statement value once loaded -- "value != value" is only ever True for
    # NaN under IEEE754, so this catches both without importing pandas into this standalone file.
    return value is None or (isinstance(value, float) and math.isnan(value))


def score_customer(feature_dict, bundle):
    # feature_dict: {feature_name: value} for at least the bundle's feature list.
    # Returns {"severity_score": float, "severity_tier": str, "lgd": float}.
    # Iterates in a fixed alphabetical order, NOT bundle["features"]'s stored order -- floating
    # point addition is not associative, so summing the same terms in a different order can shift
    # the last bit or two of the result. That is invisible almost everywhere, but a score that
    # lands extremely close to a cutpoint can round to the other side of it. Notebook 27's own
    # pipeline always sums in alphabetical feature-name order, so this must match that exactly.
    score = 0.0
    for feat in sorted(bundle["features"]):
        raw = feature_dict.get(feat)
        if _is_missing(raw):
            raw = bundle["means"][feat]  # same missing-value handling as Notebook 27
        z = (float(raw) - bundle["means"][feat]) / bundle["stds"][feat]
        score += bundle["weights"][feat] * bundle["directions"][feat] * z

    if score <= bundle["cut_low"]:
        tier = bundle["tier_order"][0]
    elif score <= bundle["cut_high"]:
        tier = bundle["tier_order"][1]
    else:
        tier = bundle["tier_order"][2]

    return {"severity_score": score, "severity_tier": tier, "lgd": bundle["lgd_by_tier"][tier]}


def top_contributing_features(feature_dict, bundle, n=3):
    """Real, exact per-feature decomposition of score_customer()'s weighted-sum severity score --
    not an approximation. Because the score IS a linear sum of weight*direction*z terms, each
    term's own real value is already the feature's exact, additive contribution to the total; this
    just recomputes those same terms (same alphabetical summation order as score_customer(), for
    the identical floating-point result) and returns the n largest by magnitude."""
    contributions = []
    for feat in sorted(bundle["features"]):
        raw = feature_dict.get(feat)
        if _is_missing(raw):
            raw = bundle["means"][feat]
        z = (float(raw) - bundle["means"][feat]) / bundle["stds"][feat]
        contribution = bundle["weights"][feat] * bundle["directions"][feat] * z
        if contribution != 0.0:
            contributions.append({"factor": feat, "contribution_to_severity_score": contribution})
    contributions.sort(key=lambda r: abs(r["contribution_to_severity_score"]), reverse=True)
    return contributions[:n]


if __name__ == "__main__":
    _bundle = load_bundle()
    _example = {f: _bundle["means"][f] for f in _bundle["features"]}
    print(score_customer(_example, _bundle))
