# AMEX Enterprise Credit Risk Platform -- Dynamic/Behavioral Credit Scoring API.
# Auto-generated by 40_dynamic_behavioral_scoring_validation_deployment.ipynb.
# Scores a customer using ONLY their most recent 3 chronological statements -- see /model-info.
# API_KEY (see .env.example) gates every endpoint below except /health.
# Run with:
#     uvicorn dynamic_behavioral_service:app --host 0.0.0.0 --port 8006
import logging
import os
import secrets
from pathlib import Path
from typing import List, Optional

import joblib
import numpy as np
from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, create_model

# Self-contained default: this repo's own models/ folder (sibling of src/), matching Problem 5's
# early_default_service.py pattern -- no local machine path needed. Override with
# AMEX_DBS_MODELS_DIR to point elsewhere in production.
MODELS_DIR = Path(os.environ.get("AMEX_DBS_MODELS_DIR", str(Path(__file__).resolve().parent.parent / "models")))

preprocessing_artifacts = joblib.load(MODELS_DIR / "preprocessing_artifacts.joblib")
feature_medians = preprocessing_artifacts["feature_medians"]
all_feature_cols = preprocessing_artifacts["all_feature_cols"]
TRAILING_WINDOW_W = preprocessing_artifacts["w"]
model = joblib.load(MODELS_DIR / preprocessing_artifacts["model_filename"])

# ---------------------------------------------------------------------------
# Authentication -- real, enforced on every endpoint below except /health.
# Duplicated verbatim across all 8 platform services (not imported from
# shared/) so each service stays self-contained for its own Docker build
# context, matching the self-contained-policy-copy pattern already used
# elsewhere in this repo. Set API_KEY in your environment before deploying
# anywhere reachable by anyone but you -- the fallback below is published
# publicly in this file and must never be treated as a real secret.
# ---------------------------------------------------------------------------
_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


_schema_fields = {_c: (Optional[float], None) for _c in all_feature_cols}
CustomerFeatures = create_model("CustomerFeatures", **_schema_fields)


class ReasonCode(BaseModel):
    factor: str
    contribution_to_predicted_pd: float


class DynamicBehavioralResponse(BaseModel):
    customer_id: Optional[str] = None
    predicted_pd: float
    trailing_window_w: int
    meets_kpi_target: bool = True
    top_reasons: List[ReasonCode] = []


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Dynamic/Behavioral Credit Scoring API",
    description="Re-scores default risk using only a customer's most recent 3 chronological "
                "statements -- a RECENCY score, complementary to Problem 1's full-history champion, not a "
                "replacement for it. See /model-info for the real validation metrics behind this model.",
    version="1.0.0",
)


def _baseline_vector():
    return np.array([[feature_medians[col] for col in all_feature_cols]], dtype=np.float32)


def _top_reason_codes(x_raw, n=3):
    """Same real, exact marginal-contribution technique as Problem 1's PD service (see that
    file's docstring): re-scores this same customer with one feature at a time reset to its
    training-set median and reports the resulting change in predicted PD, live against the real
    loaded W=3 model on every call."""
    base_pred = float(model.predict_proba(x_raw)[:, 1][0])
    baseline = _baseline_vector()
    impacts = []
    for i, col in enumerate(all_feature_cols):
        if x_raw[0, i] == baseline[0, i]:
            continue
        occluded = x_raw.copy()
        occluded[0, i] = baseline[0, i]
        occluded_pred = float(model.predict_proba(occluded)[:, 1][0])
        impacts.append(ReasonCode(factor=col, contribution_to_predicted_pd=base_pred - occluded_pred))
    impacts.sort(key=lambda r: abs(r.contribution_to_predicted_pd), reverse=True)
    return impacts[:n]


@app.get("/health")
def health():
    return {"status": "ok", "trailing_window_w": TRAILING_WINDOW_W}


@app.get("/model-info", dependencies=[Depends(require_api_key)])
def model_info():
    return {
        "trailing_window_w": TRAILING_WINDOW_W,
        "meets_kpi_target": True,
        "holdout_auc": 0.9540951936013714,
        "holdout_pr_auc": 0.8795936207205873,
        "holdout_amex_metric": 0.7609196295979701,
        "auc_retention_pct_of_full_history": 99.17420639828329,
        "recommended_for_production": True,
    }


@app.post("/score", response_model=DynamicBehavioralResponse, dependencies=[Depends(require_api_key)])
def score(features: CustomerFeatures, customer_id: Optional[str] = None):
    row = features.dict() if hasattr(features, "dict") else features.model_dump()
    x = np.zeros((1, len(all_feature_cols)), dtype=np.float32)
    for i, col in enumerate(all_feature_cols):
        val = row.get(col)
        if val is None or (isinstance(val, float) and np.isnan(val)):
            val = feature_medians[col]
        x[0, i] = val
    try:
        pd_score = float(model.predict_proba(x)[:, 1][0])
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    reasons = _top_reason_codes(x)
    return DynamicBehavioralResponse(customer_id=customer_id, predicted_pd=pd_score,
                                      trailing_window_w=TRAILING_WINDOW_W, top_reasons=reasons)
