# AMEX Enterprise Credit Risk Platform -- Risk-Adjusted Profitability Scoring Lookup API.
# Auto-generated by 68_profitability_modeling_validation_deployment.ipynb.
# Serves each customer's real precomputed PROFITABILITY_SCORE / PROFITABILITY_TIER, composed from
# Problem 12's real UNIFIED_RISK_SCORE and an ASSUMPTION-labeled revenue estimate (Notebook 66).
# Every endpoint except /health requires a valid X-API-Key header (see .env.example).
# Run with:
#     uvicorn profitability_scoring_lookup_service:app --host 0.0.0.0 --port 8013
import json
import logging
import os
import secrets
from pathlib import Path
from typing import List

import polars as pl
from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel

_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


POLICY_PATH = Path(os.environ.get("AMEX_P13_POLICY_PATH", str(Path(__file__).parent / "profitability_deployment_policy.json")))
PROFILE_PATH = Path(os.environ.get("AMEX_P13_PROFILE_PATH", str(Path(__file__).parent.parent / "data" / "data/profitability_scored_profile.parquet")))
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)

PROFITABILITY_TIER_NAMES = _POLICY["profitability_tier_names"]
CUT_LOW = _POLICY["profitability_cut_low_usd"]
CUT_HIGH = _POLICY["profitability_cut_high_usd"]
REVENUE_ASSUMPTIONS = _POLICY["revenue_assumptions"]
RECOMMENDED_FOR_PRODUCTION = _POLICY["recommended_for_production"]

_PROFILE_DF = pl.read_parquet(PROFILE_PATH)
_PROFILE_INDEX = {row["customer_ID"]: row for row in _PROFILE_DF.iter_rows(named=True)}


class ProfitabilityResponse(BaseModel):
    customer_id: str
    unified_risk_score: float
    spend_percentile_rank: float
    revenue_per_account_usd: float
    pd_adjusted_revenue_usd: float
    expected_loss_usd: float
    profitability_score_usd: float
    profitability_tier: str
    rationale: str
    reasoning: List[str] = []
    recommended_for_production: bool = RECOMMENDED_FOR_PRODUCTION


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Risk-Adjusted Profitability Scoring Lookup API",
    description="Serves each real customer's precomputed PD-adjusted profitability score. Dollar figures "
                "rest partly on explicit ASSUMPTION revenue inputs -- see /policy-info. Every endpoint "
                "except /health requires a valid X-API-Key header.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok", "profiles_loaded": len(_PROFILE_INDEX)}


@app.get("/policy-info", dependencies=[Depends(require_api_key)])
def policy_info():
    return {
        "profitability_tier_names": PROFITABILITY_TIER_NAMES,
        "profitability_tier_cuts_usd": [CUT_LOW, CUT_HIGH],
        "revenue_assumptions": REVENUE_ASSUMPTIONS,
        "recommended_for_production": RECOMMENDED_FOR_PRODUCTION,
        "profiles_loaded": len(_PROFILE_INDEX),
    }


@app.get("/profitability/{customer_id}", response_model=ProfitabilityResponse, dependencies=[Depends(require_api_key)])
def get_profitability(customer_id: str):
    row = _PROFILE_INDEX.get(customer_id)
    if row is None:
        raise HTTPException(status_code=404, detail=f"No profitability profile found for customer_id={customer_id!r}.")
    reasoning = [
        f"unified_risk_score={row['UNIFIED_RISK_SCORE']:.4f} -> revenue is PD-adjusted by "
        f"(1 - {row['UNIFIED_RISK_SCORE']:.4f}) = {1.0 - row['UNIFIED_RISK_SCORE']:.4f}",
        f"spend_percentile_rank={row['SPEND_PERCENTILE_RANK']:.4f} (real, measured) -> "
        f"revenue_multiplier={row['REVENUE_MULTIPLIER']:.4f} -> "
        f"revenue_per_account_usd=${row['REVENUE_PER_ACCOUNT_USD']:.2f} (ASSUMPTION-scaled)",
        f"expected_loss_usd=${row['EXPECTED_LOSS_USD']:.2f} "
        f"(unified_risk_score x EAD x LGD, EAD/LGD inherited from Notebook 08)",
        f"profitability_score_usd=${row['PROFITABILITY_SCORE']:.2f} -> {row['PROFITABILITY_TIER']} "
        f"(cuts: <= ${CUT_LOW:.2f} {PROFITABILITY_TIER_NAMES[0]}, "
        f"<= ${CUT_HIGH:.2f} {PROFITABILITY_TIER_NAMES[1]}, else {PROFITABILITY_TIER_NAMES[2]})",
    ]
    return ProfitabilityResponse(
        customer_id=row["customer_ID"], unified_risk_score=row["UNIFIED_RISK_SCORE"],
        spend_percentile_rank=row["SPEND_PERCENTILE_RANK"],
        revenue_per_account_usd=row["REVENUE_PER_ACCOUNT_USD"],
        pd_adjusted_revenue_usd=row["PD_ADJUSTED_REVENUE_USD"], expected_loss_usd=row["EXPECTED_LOSS_USD"],
        profitability_score_usd=row["PROFITABILITY_SCORE"], profitability_tier=row["PROFITABILITY_TIER"],
        rationale=f"PD-adjusted revenue (real relative spend rank, ASSUMPTION dollar scale) minus "
                  f"expected loss (real unified risk score x Notebook 08's real EAD/LGD).",
        reasoning=reasoning,
    )
