# AMEX Enterprise Credit Risk Platform -- Real-Time Risk-Tier Scoring API.
# Auto-generated by 22_risk_tier_deployment.ipynb. Run with:
#     uvicorn risk_tier_service:app --host 0.0.0.0 --port 8001
# Configure AMEX_PROJECT_ROOT in your environment (see .env.example) if this
# machine's project folder differs from the default baked in below.
import os
import json
from pathlib import Path
from typing import Optional

import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, create_model

PROJECT_ROOT = Path(os.environ.get("AMEX_PROJECT_ROOT", r"C:\Users\rnand\Downloads\amex-default-prediction\AMEX_Enterprise_Credit_Risk_Platform"))
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"

with open(ARTIFACTS_DIR / "project_config.json", "r", encoding="utf-8") as f:
    _config = json.load(f)
_pillar_dirs = {k: Path(v) for k, v in _config["pillar_dirs"].items()}
_model_dev_dir = _pillar_dirs["model_development"]
_models_subdir = _model_dev_dir / "models"
_risk_tier_policy_dir = _pillar_dirs["risk_tier_policy"]

with open(ARTIFACTS_DIR / "notebook_05_summary.json", "r", encoding="utf-8") as f:
    _nb05_summary = json.load(f)
CHAMPION_NAME = _nb05_summary["champion_model"]
CHAMPION_METRICS = _nb05_summary["champion_metrics"]

with open(_risk_tier_policy_dir / "risk_tier_policy.json", "r", encoding="utf-8") as f:
    RISK_TIER_POLICY = json.load(f)
_BR_THRESHOLDS = sorted(RISK_TIER_POLICY["bucketing_methods"]["business_rule"]["pd_thresholds"],
                        key=lambda b: b["tier_order"])


def assign_tier(pd_value):
    for band in _BR_THRESHOLDS:
        if band["pd_lower"] <= pd_value < band["pd_upper"]:
            return band["risk_tier"]
    return _BR_THRESHOLDS[-1]["risk_tier"]


champion_model = joblib.load(_models_subdir / (CHAMPION_NAME + ".joblib"))
preprocessing_artifacts = joblib.load(_models_subdir / "preprocessing_artifacts.joblib")
label_encoders = preprocessing_artifacts["label_encoders"]
feature_medians = preprocessing_artifacts["feature_medians"]
scaler = preprocessing_artifacts["scaler"]
all_feature_cols = preprocessing_artifacts["all_feature_cols"]
categorical_encode_cols = preprocessing_artifacts["categorical_encode_cols"]
numeric_feature_cols = preprocessing_artifacts["numeric_feature_cols"]
champion_uses_scaled = CHAMPION_NAME == "logistic_regression"

_schema_fields = {}
for _c in numeric_feature_cols:
    _schema_fields[_c] = (Optional[float], None)
for _c in categorical_encode_cols:
    _schema_fields[_c] = (Optional[str], None)
CustomerFeatures = create_model("CustomerFeatures", **_schema_fields)


class RiskTierResponse(BaseModel):
    customer_id: Optional[str] = None
    predicted_pd: float
    risk_tier: str
    tier_method: str
    champion_model: str


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Risk Tier Scoring API",
    description="Real-time PD scoring plus policy-based risk-tier classification (Notebook 19's real policy).",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok", "champion_model": CHAMPION_NAME}


@app.get("/policy-info")
def policy_info():
    return {
        "n_tiers": RISK_TIER_POLICY["n_tiers"],
        "tier_order": RISK_TIER_POLICY["tier_order"],
        "primary_method": RISK_TIER_POLICY["primary_method"],
        "business_rule_thresholds": _BR_THRESHOLDS,
    }


@app.post("/risk-tier", response_model=RiskTierResponse)
def risk_tier(features: CustomerFeatures, customer_id: Optional[str] = None):
    row = features.dict() if hasattr(features, "dict") else features.model_dump()
    x = np.zeros((1, len(all_feature_cols)), dtype=np.float32)
    for i, col in enumerate(all_feature_cols):
        val = row.get(col)
        if col in categorical_encode_cols:
            classes = label_encoders[col]["classes"]
            mapping = {cat: idx for idx, cat in enumerate(classes)}
            x[0, i] = mapping.get(val if val is not None else "__missing__", -1)
        else:
            if val is None or (isinstance(val, float) and np.isnan(val)):
                val = feature_medians[col]
            x[0, i] = val
    if champion_uses_scaled:
        x = (x - scaler["mean"]) / scaler["std"]
    try:
        pd_score = float(champion_model.predict_proba(x)[:, 1][0])
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    tier = assign_tier(pd_score)
    return RiskTierResponse(customer_id=customer_id, predicted_pd=pd_score, risk_tier=tier,
                             tier_method="business_rule", champion_model=CHAMPION_NAME)
