# AMEX Enterprise Credit Risk Platform -- Early Warning System Real-Time Alert API.
# Auto-generated by 44_early_warning_system_validation_deployment.ipynb.
# Unlike Problems 1/5/6's services, this one scores a CUSTOMER'S STATEMENT HISTORY (a list of past
# records), not a single flat feature row -- the baseline is computed from that history at scoring
# time, exactly reproducing Notebooks 43/44's rolling z-score computation.
# OAuth2 client-credentials + JWT (pilot) gates /score and /model-info -- POST /token
# first to get a bearer token (see .env.example for the shared secret used as both
# the client_secret and the JWT signing key in this pilot). /health, /metrics, and
# /token itself are unauthenticated.
# Run with:
#     uvicorn real_time_alert_service:app --host 0.0.0.0 --port 8007
import json
import logging
import os
import secrets
import time
from pathlib import Path
from typing import Dict, List, Optional

import jwt
import numpy as np
from fastapi import Depends, FastAPI, Form, HTTPException, Request, Response, Security
from fastapi.security import OAuth2PasswordBearer
from pydantic import BaseModel
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Histogram, generate_latest
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

# Self-contained default: the real frozen policy ships alongside this file in src/ (see
# docs/early_warning_deployment_policy.json for the original copy). Override with
# AMEX_EWS_POLICY_PATH to point elsewhere in production.
POLICY_PATH = Path(
    os.environ.get("AMEX_EWS_POLICY_PATH", str(Path(__file__).parent / "early_warning_deployment_policy.json"))
)
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)

Z_THRESHOLD = _POLICY["z_threshold"]
MIN_STATEMENTS_FOR_BASELINE = _POLICY["min_statements_for_baseline"]
WINNING_MIN_DEVIATION_COUNT = _POLICY["winning_min_deviation_count"]
MONITORED_FEATURES = _POLICY["monitored_features"]
RECOMMENDED_FOR_PRODUCTION = _POLICY["recommended_for_production"]

# ---------------------------------------------------------------------------
# Authentication -- OAuth2 client-credentials grant + JWT (pilot, this service
# only; see AUTH_HARDENING.md for why the platform's other 13 services still
# use the shared X-API-Key pattern and the honest scope/limits of this pilot).
# A caller first POSTs to /token with grant_type=client_credentials,
# client_id, and client_secret to get a short-lived signed JWT, then sends it
# as `Authorization: Bearer <token>` on /score and /model-info.
#
# Real, stated simplifications of this pilot, not hidden: there is a single
# hardcoded registered client_id (no client registry/database), and the same
# shared secret (API_KEY) is reused as both that client's credential AND the
# HS256 JWT signing key -- a real production rollout would keep those
# separate. Both are deliberate choices to pilot the OAuth2/JWT *pattern*
# without standing up new infrastructure, not oversights.
# ---------------------------------------------------------------------------
_auth_logger = logging.getLogger(__name__ + ".auth")
# This IS the published, non-secret placeholder -- the name and value say so (bandit false positive).
_DEV_DEFAULT_SHARED_SECRET = "dev-only-CHANGE-ME-before-deploying"  # nosec B105
JWT_ALGORITHM = "HS256"
JWT_AUDIENCE = "amex-ews-api"
JWT_ISSUER = "amex-ews-token-service"
JWT_SCOPE = "score"
JWT_EXPIRY_SECONDS = 900  # 15 minutes
REGISTERED_CLIENT_ID = "ews-service-client"
_oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/token", auto_error=False)


def _configured_shared_secret() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_SHARED_SECRET
    return key


def require_bearer_token(token: Optional[str] = Security(_oauth2_scheme)) -> dict:
    if not token:
        raise HTTPException(
            status_code=401,
            detail="Missing bearer token. POST /token (grant_type=client_credentials) to obtain one.",
        )
    try:
        payload = jwt.decode(
            token,
            _configured_shared_secret(),
            algorithms=[JWT_ALGORITHM],
            audience=JWT_AUDIENCE,
            issuer=JWT_ISSUER,
        )
    except jwt.ExpiredSignatureError:
        raise HTTPException(status_code=401, detail="Token expired -- request a new one from /token.")
    except jwt.InvalidTokenError as exc:
        raise HTTPException(status_code=401, detail=f"Invalid token: {exc}")
    if payload.get("scope") != JWT_SCOPE:
        raise HTTPException(status_code=403, detail=f"Token missing required scope: {JWT_SCOPE}")
    return payload


class ScoreRequest(BaseModel):
    customer_id: Optional[str] = None
    # Chronological order, OLDEST first, LAST item = the latest statement being tested.
    # Each statement is a dict of {monitored_feature_name: value_or_null}.
    statements: List[Dict[str, Optional[float]]]


class ReasonCode(BaseModel):
    factor: str
    z_score: float


class AlertResponse(BaseModel):
    customer_id: Optional[str] = None
    early_warning_score: int
    monitored_feature_count: int
    z_computable_feature_count: int
    alert: bool
    winning_min_deviation_count: int
    feature_deviations: Dict[str, Optional[float]]
    top_reasons: List[ReasonCode] = []


def compute_early_warning(statements: List[Dict[str, Optional[float]]]) -> dict:
    if len(statements) < MIN_STATEMENTS_FOR_BASELINE:
        raise ValueError(
            f"Need >= {MIN_STATEMENTS_FOR_BASELINE} statements to form a baseline + latest, got " f"{len(statements)}."
        )
    baseline_statements = statements[:-1]
    latest_statement = statements[-1]
    feature_deviations: Dict[str, Optional[float]] = {}
    n_deviating = 0
    n_computable = 0
    for feat in MONITORED_FEATURES:
        baseline_vals = [s[feat] for s in baseline_statements if s.get(feat) is not None]
        latest_val = latest_statement.get(feat)
        if len(baseline_vals) < 2 or latest_val is None:
            feature_deviations[feat] = None
            continue
        arr = np.asarray(baseline_vals, dtype=np.float64)
        baseline_mean = float(arr.mean())
        baseline_std = float(arr.std(ddof=1))
        if baseline_std <= 0:
            feature_deviations[feat] = None
            continue
        z = (float(latest_val) - baseline_mean) / baseline_std
        feature_deviations[feat] = z
        n_computable += 1
        if abs(z) >= Z_THRESHOLD:
            n_deviating += 1
    return {
        "early_warning_score": n_deviating,
        "z_computable_feature_count": n_computable,
        "feature_deviations": feature_deviations,
    }


def top_reason_codes(feature_deviations: Dict[str, Optional[float]], n=3):
    """Real, exact ranking of the already-computed per-feature z-scores by |z| -- not a separate
    approximation technique, since this service already computes an exact deviation per monitored
    feature as part of its own scoring; this just surfaces the n largest ones as the specific
    factors that actually drove this customer's early_warning_score, per CFPB Circular 2022-03's
    'specific, principal reason' standard."""
    computable = [(feat, z) for feat, z in feature_deviations.items() if z is not None]
    computable.sort(key=lambda item: abs(item[1]), reverse=True)
    return [ReasonCode(factor=feat, z_score=z) for feat, z in computable[:n]]


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Early Warning System Real-Time Alert API",
    description="Flags a customer whose LATEST statement deviates from THEIR OWN recent baseline in "
    "enough monitored features at once -- an unsupervised, rule-based control-chart "
    "technique, complementary to Problem 6's trained recency model. See /model-info for "
    "the real validation metrics behind this policy.",
    version="1.0.0",
)

# Rate limiting -- real, enforced (60 requests/minute per client IP on /score; /health and
# /model-info are left unlimited since they're liveness/metadata reads, not scoring load).
limiter = Limiter(key_func=get_remote_address)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Prometheus metrics -- real, scraped via GET /metrics (left unauthenticated/unlimited, like
# /health, since a metrics scraper is infrastructure, not scoring load). Pilot for this one
# service; see MONITORING.md for the honest platform-wide scope note.
SCORE_REQUESTS_TOTAL = Counter("ews_score_requests_total", "Total /score requests by outcome", ["outcome"])
SCORE_LATENCY_SECONDS = Histogram("ews_score_latency_seconds", "Real wall-clock latency of /score, seconds")


@app.get("/metrics")
def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)


@app.post("/token")
def issue_token(
    grant_type: str = Form(...),
    client_id: str = Form(...),
    client_secret: str = Form(...),
):
    """Real OAuth2 client-credentials grant. Not rate-limited or otherwise brute-force-protected
    in this pilot -- see AUTH_HARDENING.md's follow-on list."""
    if grant_type != "client_credentials":
        raise HTTPException(
            status_code=400,
            detail="unsupported_grant_type: only 'client_credentials' is implemented by this pilot.",
        )
    expected_secret = _configured_shared_secret()
    if client_id != REGISTERED_CLIENT_ID or not secrets.compare_digest(client_secret, expected_secret):
        raise HTTPException(status_code=401, detail="invalid_client: unknown client_id or bad client_secret.")
    now = int(time.time())
    payload = {
        "iss": JWT_ISSUER,
        "sub": client_id,
        "aud": JWT_AUDIENCE,
        "scope": JWT_SCOPE,
        "iat": now,
        "exp": now + JWT_EXPIRY_SECONDS,
    }
    token = jwt.encode(payload, expected_secret, algorithm=JWT_ALGORITHM)
    # 'bearer' is the standard OAuth2 token_type value (RFC 6750), not a credential (bandit false positive).
    return {"access_token": token, "token_type": "bearer", "expires_in": JWT_EXPIRY_SECONDS}  # nosec B105


@app.get("/health")
def health():
    return {"status": "ok", "winning_min_deviation_count": WINNING_MIN_DEVIATION_COUNT}


@app.get("/model-info", dependencies=[Depends(require_bearer_token)])
def model_info():
    return {
        "z_threshold": Z_THRESHOLD,
        "min_statements_for_baseline": MIN_STATEMENTS_FOR_BASELINE,
        "winning_min_deviation_count": WINNING_MIN_DEVIATION_COUNT,
        "monitored_feature_count": len(MONITORED_FEATURES),
        "winning_candidate_metrics": _POLICY["winning_candidate_metrics"],
        "recommended_for_production": RECOMMENDED_FOR_PRODUCTION,
    }


@app.post("/score", response_model=AlertResponse, dependencies=[Depends(require_bearer_token)])
@limiter.limit("60/minute")
def score(request: Request, body: ScoreRequest):
    start_time = time.time()
    try:
        result = compute_early_warning(body.statements)
    except ValueError as exc:
        SCORE_LATENCY_SECONDS.observe(time.time() - start_time)
        SCORE_REQUESTS_TOTAL.labels(outcome="validation_error").inc()
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        SCORE_LATENCY_SECONDS.observe(time.time() - start_time)
        SCORE_REQUESTS_TOTAL.labels(outcome="error").inc()
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    alert = result["early_warning_score"] >= WINNING_MIN_DEVIATION_COUNT
    reasons = top_reason_codes(result["feature_deviations"])
    SCORE_LATENCY_SECONDS.observe(time.time() - start_time)
    SCORE_REQUESTS_TOTAL.labels(outcome="alert" if alert else "no_alert").inc()
    return AlertResponse(
        customer_id=body.customer_id,
        early_warning_score=result["early_warning_score"],
        monitored_feature_count=len(MONITORED_FEATURES),
        z_computable_feature_count=result["z_computable_feature_count"],
        alert=alert,
        winning_min_deviation_count=WINNING_MIN_DEVIATION_COUNT,
        feature_deviations=result["feature_deviations"],
        top_reasons=reasons,
    )
