# AMEX Enterprise Credit Risk Platform -- Early Warning System Real-Time Alert API.
# Auto-generated by 44_early_warning_system_validation_deployment.ipynb.
# Unlike Problems 1/5/6's services, this one scores a CUSTOMER'S STATEMENT HISTORY (a list of past
# records), not a single flat feature row -- the baseline is computed from that history at scoring
# time, exactly reproducing Notebooks 43/44's rolling z-score computation.
# API_KEY (see .env.example) gates every endpoint below except /health.
# Run with:
#     uvicorn real_time_alert_service:app --host 0.0.0.0 --port 8007
import json
import logging
import os
import secrets
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel

# Self-contained default: the real frozen policy ships alongside this file in src/ (see
# docs/early_warning_deployment_policy.json for the original copy). Override with
# AMEX_EWS_POLICY_PATH to point elsewhere in production.
POLICY_PATH = Path(os.environ.get("AMEX_EWS_POLICY_PATH", str(Path(__file__).parent / "early_warning_deployment_policy.json")))
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)

Z_THRESHOLD = _POLICY["z_threshold"]
MIN_STATEMENTS_FOR_BASELINE = _POLICY["min_statements_for_baseline"]
WINNING_MIN_DEVIATION_COUNT = _POLICY["winning_min_deviation_count"]
MONITORED_FEATURES = _POLICY["monitored_features"]
RECOMMENDED_FOR_PRODUCTION = _POLICY["recommended_for_production"]

# ---------------------------------------------------------------------------
# Authentication -- real, enforced on every endpoint below except /health.
# Duplicated verbatim across all 8 platform services (not imported from
# shared/) so each service stays self-contained for its own Docker build
# context, matching the self-contained-policy-copy pattern already used
# elsewhere in this repo. Set API_KEY in your environment before deploying
# anywhere reachable by anyone but you -- the fallback below is published
# publicly in this file and must never be treated as a real secret.
# ---------------------------------------------------------------------------
_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


class ScoreRequest(BaseModel):
    customer_id: Optional[str] = None
    # Chronological order, OLDEST first, LAST item = the latest statement being tested.
    # Each statement is a dict of {monitored_feature_name: value_or_null}.
    statements: List[Dict[str, Optional[float]]]


class ReasonCode(BaseModel):
    factor: str
    z_score: float


class AlertResponse(BaseModel):
    customer_id: Optional[str] = None
    early_warning_score: int
    monitored_feature_count: int
    z_computable_feature_count: int
    alert: bool
    winning_min_deviation_count: int
    feature_deviations: Dict[str, Optional[float]]
    top_reasons: List[ReasonCode] = []


def compute_early_warning(statements: List[Dict[str, Optional[float]]]) -> dict:
    if len(statements) < MIN_STATEMENTS_FOR_BASELINE:
        raise ValueError(
            f"Need >= {MIN_STATEMENTS_FOR_BASELINE} statements to form a baseline + latest, got "
            f"{len(statements)}."
        )
    baseline_statements = statements[:-1]
    latest_statement = statements[-1]
    feature_deviations: Dict[str, Optional[float]] = {}
    n_deviating = 0
    n_computable = 0
    for feat in MONITORED_FEATURES:
        baseline_vals = [s[feat] for s in baseline_statements if s.get(feat) is not None]
        latest_val = latest_statement.get(feat)
        if len(baseline_vals) < 2 or latest_val is None:
            feature_deviations[feat] = None
            continue
        arr = np.asarray(baseline_vals, dtype=np.float64)
        baseline_mean = float(arr.mean())
        baseline_std = float(arr.std(ddof=1))
        if baseline_std <= 0:
            feature_deviations[feat] = None
            continue
        z = (float(latest_val) - baseline_mean) / baseline_std
        feature_deviations[feat] = z
        n_computable += 1
        if abs(z) >= Z_THRESHOLD:
            n_deviating += 1
    return {
        "early_warning_score": n_deviating,
        "z_computable_feature_count": n_computable,
        "feature_deviations": feature_deviations,
    }


def top_reason_codes(feature_deviations: Dict[str, Optional[float]], n=3):
    """Real, exact ranking of the already-computed per-feature z-scores by |z| -- not a separate
    approximation technique, since this service already computes an exact deviation per monitored
    feature as part of its own scoring; this just surfaces the n largest ones as the specific
    factors that actually drove this customer's early_warning_score, per CFPB Circular 2022-03's
    'specific, principal reason' standard."""
    computable = [(feat, z) for feat, z in feature_deviations.items() if z is not None]
    computable.sort(key=lambda item: abs(item[1]), reverse=True)
    return [ReasonCode(factor=feat, z_score=z) for feat, z in computable[:n]]


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Early Warning System Real-Time Alert API",
    description="Flags a customer whose LATEST statement deviates from THEIR OWN recent baseline in "
                "enough monitored features at once -- an unsupervised, rule-based control-chart "
                "technique, complementary to Problem 6's trained recency model. See /model-info for "
                "the real validation metrics behind this policy.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok", "winning_min_deviation_count": WINNING_MIN_DEVIATION_COUNT}


@app.get("/model-info", dependencies=[Depends(require_api_key)])
def model_info():
    return {
        "z_threshold": Z_THRESHOLD,
        "min_statements_for_baseline": MIN_STATEMENTS_FOR_BASELINE,
        "winning_min_deviation_count": WINNING_MIN_DEVIATION_COUNT,
        "monitored_feature_count": len(MONITORED_FEATURES),
        "winning_candidate_metrics": _POLICY["winning_candidate_metrics"],
        "recommended_for_production": RECOMMENDED_FOR_PRODUCTION,
    }


@app.post("/score", response_model=AlertResponse, dependencies=[Depends(require_api_key)])
def score(request: ScoreRequest):
    try:
        result = compute_early_warning(request.statements)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    alert = result["early_warning_score"] >= WINNING_MIN_DEVIATION_COUNT
    reasons = top_reason_codes(result["feature_deviations"])
    return AlertResponse(
        customer_id=request.customer_id,
        early_warning_score=result["early_warning_score"],
        monitored_feature_count=len(MONITORED_FEATURES),
        z_computable_feature_count=result["z_computable_feature_count"],
        alert=alert,
        winning_min_deviation_count=WINNING_MIN_DEVIATION_COUNT,
        feature_deviations=result["feature_deviations"],
        top_reasons=reasons,
    )
