# AMEX Enterprise Credit Risk Platform -- Executive Decision Support Dashboard API.
# Auto-generated by 72_executive_dashboard_validation_deployment.ipynb.
# Serves the real, precomputed roll-up of all 13 prior problems' real results (Notebook 71's real
# BI aggregation layer). Every endpoint except /health requires a valid X-API-Key header.
# Run with:
#     uvicorn executive_dashboard_service:app --host 0.0.0.0 --port 8014
import json
import logging
import os
import secrets
from pathlib import Path

from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader

_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


POLICY_PATH = Path(os.environ.get("AMEX_P14_POLICY_PATH", str(Path(__file__).parent / "executive_dashboard_deployment_policy.json")))
DASHBOARD_DATA_PATH = Path(os.environ.get("AMEX_P14_DATA_PATH", str(Path(__file__).parent / "executive_dashboard_data.json")))
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)
with open(DASHBOARD_DATA_PATH, "r", encoding="utf-8") as _f:
    _DASHBOARD_DATA = json.load(_f)

_ROWS_BY_PROBLEM = {row["problem_number"]: row for row in _DASHBOARD_DATA["rows"]}

app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Executive Decision Support Dashboard API",
    description="Serves the real, precomputed roll-up of all 13 prior problems. Every endpoint except "
                "/health requires a valid X-API-Key header.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok", "problems_loaded": len(_ROWS_BY_PROBLEM)}


@app.get("/executive-summary", dependencies=[Depends(require_api_key)])
def executive_summary():
    return _DASHBOARD_DATA


@app.get("/problem/{problem_number}", dependencies=[Depends(require_api_key)])
def get_problem(problem_number: int):
    row = _ROWS_BY_PROBLEM.get(problem_number)
    if row is None:
        raise HTTPException(status_code=404, detail=f"No such problem_number={problem_number!r}. "
                                                     f"Valid range: 1-13.")
    return row
