# AMEX Enterprise Credit Risk Platform -- Real-Time Portfolio Monitoring Ops Dashboard + Alert Feed API.
# Auto-generated by 60_real_time_portfolio_monitoring_validation_deployment.ipynb.
# Genuinely different deployment shape from every prior problem's per-customer scoring service: this
# ingests ONE REAL CALENDAR MONTH's portfolio-wide aggregate at a time (what a monthly production batch
# job would compute and push), maintains a running history server-side, and exposes the full alert feed.
# Every endpoint except /health requires a valid X-API-Key header (see .env.example).
# Run with:
#     uvicorn portfolio_alert_feed_service:app --host 0.0.0.0 --port 8011
import json
import logging
import os
import secrets
from pathlib import Path
from typing import Dict, List, Optional

from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel

_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


POLICY_PATH = Path(os.environ.get("AMEX_P11_POLICY_PATH", r"C:\Users\rnand\Downloads\amex-default-prediction\AMEX_Enterprise_Credit_Risk_Platform\Phase4_Operational_Risk_Management\Problem11_Real_Time_Portfolio_Monitoring\models\portfolio_monitoring_deployment_policy.json"))
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)

CONTROL_LIMIT_K_SIGMA = _POLICY["control_limit_k_sigma"]
MIN_TRAILING_MONTHS_FOR_BASELINE = _POLICY["min_trailing_months_for_baseline"]
WINNING_CONSECUTIVE_BREACH_CANDIDATE = _POLICY["winning_consecutive_breach_candidate"]
MONITORED_BASE_COLUMNS = _POLICY["monitored_base_columns"]
RECOMMENDED_FOR_PRODUCTION = _POLICY["recommended_for_production"]

# In-memory running monthly history -- the real, persistent alert feed. A production deployment would
# back this with a small database table instead of a process-lifetime list; the algorithm is identical.
_HISTORY: List[dict] = []
_CONSECUTIVE_BREACH_RUN_LENGTH = 0


class MonthIngestRequest(BaseModel):
    month: str  # ISO date, first-of-month, e.g. "2018-04-01"
    n_statements: int
    n_unique_customers: int
    # {monitored_base_column: portfolio_mean_value_or_null}
    column_means: Dict[str, Optional[float]]


class MonthStatus(BaseModel):
    month: str
    n_statements: int
    n_unique_customers: int
    baseline_eligible: bool
    breach_per_column: Dict[str, bool]
    breach_count: int
    consecutive_breach_run_length: int
    alert: bool


def _compute_month_status(req: MonthIngestRequest) -> MonthStatus:
    global _CONSECUTIVE_BREACH_RUN_LENGTH
    _idx = len(_HISTORY)
    baseline_eligible = _idx >= MIN_TRAILING_MONTHS_FOR_BASELINE
    breach_per_column: Dict[str, bool] = {}
    breach_count = 0
    if baseline_eligible:
        for col in MONITORED_BASE_COLUMNS:
            _baseline_vals = [
                h["column_means"].get(col) for h in _HISTORY
                if h["column_means"].get(col) is not None
            ]
            _current = req.column_means.get(col)
            if len(_baseline_vals) < 2 or _current is None:
                breach_per_column[col] = False
                continue
            _arr = _baseline_vals
            _n = len(_arr)
            _mean = sum(_arr) / _n
            _var = sum((v - _mean) ** 2 for v in _arr) / (_n - 1)
            _std = _var ** 0.5
            if _std <= 0:
                breach_per_column[col] = False
                continue
            _z = (_current - _mean) / _std
            _breach = abs(_z) >= CONTROL_LIMIT_K_SIGMA
            breach_per_column[col] = _breach
            if _breach:
                breach_count += 1
    else:
        breach_per_column = {col: False for col in MONITORED_BASE_COLUMNS}

    _breaching_month = baseline_eligible and breach_count >= 1
    if _breaching_month:
        _CONSECUTIVE_BREACH_RUN_LENGTH += 1
    else:
        _CONSECUTIVE_BREACH_RUN_LENGTH = 0
    alert = _CONSECUTIVE_BREACH_RUN_LENGTH >= WINNING_CONSECUTIVE_BREACH_CANDIDATE

    status = MonthStatus(
        month=req.month, n_statements=req.n_statements, n_unique_customers=req.n_unique_customers,
        baseline_eligible=baseline_eligible, breach_per_column=breach_per_column, breach_count=breach_count,
        consecutive_breach_run_length=_CONSECUTIVE_BREACH_RUN_LENGTH, alert=alert,
    )
    _HISTORY.append({"month": req.month, "n_statements": req.n_statements,
                      "n_unique_customers": req.n_unique_customers, "column_means": req.column_means,
                      "status": status.dict()})
    return status


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Real-Time Portfolio Monitoring Ops Dashboard + Alert Feed API",
    description="Ingests one real calendar month's whole-portfolio aggregate at a time and maintains "
                "the running alert feed a monitoring dashboard renders -- a genuinely different "
                "deployment shape from every prior problem's per-customer scoring service. Every "
                "endpoint except /health requires a valid X-API-Key header.",
    version="1.0.0",
)


@app.get("/health")
def health():
    _current_alert = _HISTORY[-1]["status"]["alert"] if _HISTORY else False
    return {"status": "ok", "n_months_ingested": len(_HISTORY), "current_alert_state": _current_alert}


@app.get("/policy-info", dependencies=[Depends(require_api_key)])
def policy_info():
    return {
        "control_limit_k_sigma": CONTROL_LIMIT_K_SIGMA,
        "min_trailing_months_for_baseline": MIN_TRAILING_MONTHS_FOR_BASELINE,
        "winning_consecutive_breach_candidate": WINNING_CONSECUTIVE_BREACH_CANDIDATE,
        "monitored_base_columns": MONITORED_BASE_COLUMNS,
        "winning_candidate_metrics": _POLICY["winning_candidate_metrics"],
        "recommended_for_production": RECOMMENDED_FOR_PRODUCTION,
    }


@app.post("/ingest-month", response_model=MonthStatus, dependencies=[Depends(require_api_key)])
def ingest_month(request: MonthIngestRequest):
    try:
        return _compute_month_status(request)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Ingestion failed: " + str(exc))


@app.get("/alert-feed", dependencies=[Depends(require_api_key)])
def alert_feed():
    return {"n_months": len(_HISTORY), "months": [h["status"] for h in _HISTORY]}


@app.post("/reset", dependencies=[Depends(require_api_key)])
def reset():
    """Clears the in-memory history -- for tests/re-seeding only, never called by a real dashboard."""
    global _CONSECUTIVE_BREACH_RUN_LENGTH
    _HISTORY.clear()
    _CONSECUTIVE_BREACH_RUN_LENGTH = 0
    return {"status": "reset"}
