# AMEX Enterprise Credit Risk Platform -- Early Warning System Real-Time Alert API.
# Auto-generated by 44_early_warning_system_validation_deployment.ipynb.
# Unlike Problems 1/5/6's services, this one scores a CUSTOMER'S STATEMENT HISTORY (a list of past
# records), not a single flat feature row -- the baseline is computed from that history at scoring
# time, exactly reproducing Notebooks 43/44's rolling z-score computation.
# Run with:
#     uvicorn real_time_alert_service:app --host 0.0.0.0 --port 8004
import json
import os
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

POLICY_PATH = Path(os.environ.get("AMEX_EWS_POLICY_PATH", r"C:\Users\rnand\Downloads\amex-default-prediction\AMEX_Enterprise_Credit_Risk_Platform\Phase3_Behavioral_Intelligence\Problem7_Early_Warning_System\models\early_warning_deployment_policy.json"))
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)

Z_THRESHOLD = _POLICY["z_threshold"]
MIN_STATEMENTS_FOR_BASELINE = _POLICY["min_statements_for_baseline"]
WINNING_MIN_DEVIATION_COUNT = _POLICY["winning_min_deviation_count"]
MONITORED_FEATURES = _POLICY["monitored_features"]
RECOMMENDED_FOR_PRODUCTION = _POLICY["recommended_for_production"]


class ScoreRequest(BaseModel):
    customer_id: Optional[str] = None
    # Chronological order, OLDEST first, LAST item = the latest statement being tested.
    # Each statement is a dict of {monitored_feature_name: value_or_null}.
    statements: List[Dict[str, Optional[float]]]


class AlertResponse(BaseModel):
    customer_id: Optional[str] = None
    early_warning_score: int
    monitored_feature_count: int
    z_computable_feature_count: int
    alert: bool
    winning_min_deviation_count: int
    feature_deviations: Dict[str, Optional[float]]


def compute_early_warning(statements: List[Dict[str, Optional[float]]]) -> dict:
    if len(statements) < MIN_STATEMENTS_FOR_BASELINE:
        raise ValueError(
            f"Need >= {MIN_STATEMENTS_FOR_BASELINE} statements to form a baseline + latest, got "
            f"{len(statements)}."
        )
    baseline_statements = statements[:-1]
    latest_statement = statements[-1]
    feature_deviations: Dict[str, Optional[float]] = {}
    n_deviating = 0
    n_computable = 0
    for feat in MONITORED_FEATURES:
        baseline_vals = [s[feat] for s in baseline_statements if s.get(feat) is not None]
        latest_val = latest_statement.get(feat)
        if len(baseline_vals) < 2 or latest_val is None:
            feature_deviations[feat] = None
            continue
        arr = np.asarray(baseline_vals, dtype=np.float64)
        baseline_mean = float(arr.mean())
        baseline_std = float(arr.std(ddof=1))
        if baseline_std <= 0:
            feature_deviations[feat] = None
            continue
        z = (float(latest_val) - baseline_mean) / baseline_std
        feature_deviations[feat] = z
        n_computable += 1
        if abs(z) >= Z_THRESHOLD:
            n_deviating += 1
    return {
        "early_warning_score": n_deviating,
        "z_computable_feature_count": n_computable,
        "feature_deviations": feature_deviations,
    }


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Early Warning System Real-Time Alert API",
    description="Flags a customer whose LATEST statement deviates from THEIR OWN recent baseline in "
                "enough monitored features at once -- an unsupervised, rule-based control-chart "
                "technique, complementary to Problem 6's trained recency model. See /model-info for "
                "the real validation metrics behind this policy.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok", "winning_min_deviation_count": WINNING_MIN_DEVIATION_COUNT}


@app.get("/model-info")
def model_info():
    return {
        "z_threshold": Z_THRESHOLD,
        "min_statements_for_baseline": MIN_STATEMENTS_FOR_BASELINE,
        "winning_min_deviation_count": WINNING_MIN_DEVIATION_COUNT,
        "monitored_feature_count": len(MONITORED_FEATURES),
        "winning_candidate_metrics": _POLICY["winning_candidate_metrics"],
        "recommended_for_production": RECOMMENDED_FOR_PRODUCTION,
    }


@app.post("/score", response_model=AlertResponse)
def score(request: ScoreRequest):
    try:
        result = compute_early_warning(request.statements)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    alert = result["early_warning_score"] >= WINNING_MIN_DEVIATION_COUNT
    return AlertResponse(
        customer_id=request.customer_id,
        early_warning_score=result["early_warning_score"],
        monitored_feature_count=len(MONITORED_FEATURES),
        z_computable_feature_count=result["z_computable_feature_count"],
        alert=alert,
        winning_min_deviation_count=WINNING_MIN_DEVIATION_COUNT,
        feature_deviations=result["feature_deviations"],
    )
