# AMEX Enterprise Credit Risk Platform -- Credit Line Management Recommendation API.
# Auto-generated by 56_credit_line_management_validation_deployment.ipynb.
# Composes a customer's real static PD (Problem 1) and real dynamic PD (Problem 6) into a risk-level
# x trend classification and a real credit-line action recommendation.
# Every endpoint except /health requires a valid X-API-Key header (see .env.example).
# Run with:
#     uvicorn credit_line_scoring_service:app --host 0.0.0.0 --port 8010
import json
import logging
import os
import secrets
from pathlib import Path
from typing import List, Optional

from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel

_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


POLICY_PATH = Path(os.environ.get("AMEX_P10_POLICY_PATH", str(Path(__file__).parent / "credit_line_deployment_policy.json")))
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)

RISK_LEVEL_NAMES = _POLICY["risk_level_names"]
TREND_NAMES = _POLICY["trend_names"]
RISK_LEVEL_CUT_LOW = _POLICY["risk_level_cut_low"]
RISK_LEVEL_CUT_HIGH = _POLICY["risk_level_cut_high"]
TREND_CUT_LOW = _POLICY["trend_cut_low"]
TREND_CUT_HIGH = _POLICY["trend_cut_high"]
ACTION_MAP = {(c["risk_level"], c["trend"]): c for c in _POLICY["action_tier_matrix"]}
RECOMMENDED_FOR_PRODUCTION = _POLICY["recommended_for_production"]
UTILIZATION_TREND_NOTE = _POLICY["utilization_trend_reinterpretation"]


class RecommendRequest(BaseModel):
    customer_id: Optional[str] = None
    static_pd: float
    dynamic_pd: float


class RecommendResponse(BaseModel):
    customer_id: Optional[str] = None
    static_pd: float
    dynamic_pd: float
    pd_trend: float
    risk_level: str
    trend: str
    action: str
    rationale: str
    reasoning: List[str] = []
    recommended_for_production: bool = RECOMMENDED_FOR_PRODUCTION


def _assign_risk_level(dynamic_pd: float) -> str:
    if dynamic_pd <= RISK_LEVEL_CUT_LOW:
        return RISK_LEVEL_NAMES[0]
    if dynamic_pd <= RISK_LEVEL_CUT_HIGH:
        return RISK_LEVEL_NAMES[1]
    return RISK_LEVEL_NAMES[2]


def _assign_trend(pd_trend: float) -> str:
    if pd_trend <= TREND_CUT_LOW:
        return TREND_NAMES[0]
    if pd_trend <= TREND_CUT_HIGH:
        return TREND_NAMES[1]
    return TREND_NAMES[2]


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Credit Line Management Recommendation API",
    description="Composes real static + dynamic PD scores into a risk-level x trend classification "
                "and a real credit-line action recommendation. Every endpoint except /health requires "
                "a valid X-API-Key header.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/policy-info", dependencies=[Depends(require_api_key)])
def policy_info():
    return {
        "risk_level_names": RISK_LEVEL_NAMES,
        "trend_names": TREND_NAMES,
        "risk_level_cuts": [RISK_LEVEL_CUT_LOW, RISK_LEVEL_CUT_HIGH],
        "trend_cuts": [TREND_CUT_LOW, TREND_CUT_HIGH],
        "action_tier_matrix": _POLICY["action_tier_matrix"],
        "recommended_for_production": RECOMMENDED_FOR_PRODUCTION,
        "utilization_trend_note": UTILIZATION_TREND_NOTE,
    }


@app.post("/recommend", response_model=RecommendResponse, dependencies=[Depends(require_api_key)])
def recommend(request: RecommendRequest):
    if not (0.0 <= request.static_pd <= 1.0) or not (0.0 <= request.dynamic_pd <= 1.0):
        raise HTTPException(status_code=422, detail="static_pd and dynamic_pd must both be in [0, 1].")
    pd_trend = request.dynamic_pd - request.static_pd
    risk_level = _assign_risk_level(request.dynamic_pd)
    trend = _assign_trend(pd_trend)
    cell = ACTION_MAP.get((risk_level, trend))
    if cell is None:
        raise HTTPException(status_code=500, detail=f"No action defined for ({risk_level}, {trend}).")
    reasoning = [
        f"dynamic_pd={request.dynamic_pd:.4f} -> {risk_level} "
        f"(cuts: <= {RISK_LEVEL_CUT_LOW:.4f} Low, <= {RISK_LEVEL_CUT_HIGH:.4f} Medium, else High)",
        f"pd_trend={pd_trend:.4f} (dynamic_pd - static_pd) -> {trend} "
        f"(cuts: <= {TREND_CUT_LOW:.4f} Better, <= {TREND_CUT_HIGH:.4f} Stable, else Worse)",
        f"({risk_level}, {trend}) -> {cell['action']}",
    ]
    return RecommendResponse(
        customer_id=request.customer_id, static_pd=request.static_pd, dynamic_pd=request.dynamic_pd,
        pd_trend=pd_trend, risk_level=risk_level, trend=trend, action=cell["action"],
        rationale=cell["rationale"], reasoning=reasoning,
    )
