# Standalone Expected Credit Loss (ECL) calculator for Problem 3 (IFRS9/CECL). Generated by
# Notebook 32 -- loads ecl_scoring_bundle.json (saved alongside this file) and computes IFRS9-staged
# and CECL ECL for one customer, given their real PD (from Problem 1's own deployed model -- NOT
# reproduced here) and real severity tier (from Problem 4's own deployed model). No training or
# staging-threshold-fitting happens here; every parameter is frozen from Notebook 30's real policy.
import json
from pathlib import Path

BUNDLE_PATH = Path(__file__).parent / "ecl_scoring_bundle.json"


def load_bundle(path=BUNDLE_PATH):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def compute_ecl(pd_12m, severity_tier, bundle):
    # pd_12m: float, this customer's real 12-month PD (from Problem 1's champion model).
    # severity_tier: str, one of bundle["tier_order"] (from Problem 4's real severity model).
    # Returns a dict with the IFRS9 stage, IFRS9 ECL, CECL ECL, and the intermediate PD figures --
    # matching Notebook 31's own real computation exactly (same order of operations, same rounding
    # behavior: none -- every intermediate value stays full float precision throughout).
    pd_12m = float(pd_12m)
    pd_lifetime = min(1.0, pd_12m * bundle["lifetime_pd_multiplier"])

    pd_12m_macro = 0.0
    pd_lifetime_macro = 0.0
    for s in bundle["macro_scenarios"]:
        pd_12m_macro += s["probability"] * min(1.0, pd_12m * s["pd_multiplier"])
        pd_lifetime_macro += s["probability"] * min(1.0, pd_lifetime * s["pd_multiplier"])

    is_severe = severity_tier == "Severe"
    is_elevated_tier = severity_tier in ("Moderate Severity", "Severe")
    sicr_threshold = bundle["portfolio_avg_pd_12m"] * bundle["sicr_pd_multiple"]
    if is_severe and pd_12m > bundle["stage3_pd_threshold"]:
        stage = 3
    elif (pd_12m > sicr_threshold) or is_elevated_tier:
        stage = 2
    else:
        stage = 1

    lgd = bundle["lgd_by_tier"][severity_tier]
    ead = bundle["ead_per_account_usd"]
    if stage == 1:
        ecl_ifrs9 = pd_12m_macro * lgd * ead * bundle["discount_factor_stage1"]
    else:
        ecl_ifrs9 = pd_lifetime_macro * lgd * ead * bundle["discount_factor_stage23"]
    ecl_cecl = pd_lifetime_macro * lgd * ead * bundle["discount_factor_stage23"]

    return {"ifrs9_stage": stage, "ecl_ifrs9_usd": ecl_ifrs9, "ecl_cecl_usd": ecl_cecl,
            "pd_lifetime": pd_lifetime, "pd_12m_macro_adj": pd_12m_macro,
            "pd_lifetime_macro_adj": pd_lifetime_macro}


def explain_ecl(pd_12m, severity_tier, bundle):
    """Real, exact explanation of why compute_ecl() returned what it did -- not an approximation.
    Unlike Problems 1/2/5/6's trained models, this technique is a fully interpretable, deterministic
    rule engine with exactly two customer-level inputs (pd_12m, severity_tier), so its 'reason
    codes' are simply a true narration of which branch was taken and which frozen policy values
    drove the result -- more exact than any sampled attribution method could be, since there is
    nothing left to approximate."""
    pd_12m = float(pd_12m)
    sicr_threshold = bundle["portfolio_avg_pd_12m"] * bundle["sicr_pd_multiple"]
    is_severe = severity_tier == "Severe"
    is_elevated_tier = severity_tier in ("Moderate Severity", "Severe")
    reasons = []
    if is_severe and pd_12m > bundle["stage3_pd_threshold"]:
        reasons.append({
            "factor": "severity_tier + pd_12m",
            "detail": f"severity_tier='Severe' AND pd_12m ({pd_12m:.4f}) > stage3_pd_threshold "
                      f"({bundle['stage3_pd_threshold']:.4f}) -> IFRS9 Stage 3 (lifetime ECL, no discount concession)",
        })
    elif pd_12m > sicr_threshold or is_elevated_tier:
        trigger = "pd_12m exceeds the SICR threshold" if pd_12m > sicr_threshold else "severity_tier is an elevated tier"
        reasons.append({
            "factor": "severity_tier" if is_elevated_tier and pd_12m <= sicr_threshold else "pd_12m",
            "detail": f"{trigger} (pd_12m={pd_12m:.4f}, SICR threshold={sicr_threshold:.4f}, "
                      f"severity_tier={severity_tier!r}) -> IFRS9 Stage 2 (lifetime ECL)",
        })
    else:
        reasons.append({
            "factor": "pd_12m + severity_tier",
            "detail": f"pd_12m ({pd_12m:.4f}) <= SICR threshold ({sicr_threshold:.4f}) and "
                      f"severity_tier ({severity_tier!r}) is not elevated -> IFRS9 Stage 1 (12-month ECL only)",
        })
    lgd = bundle["lgd_by_tier"][severity_tier]
    reasons.append({
        "factor": "severity_tier LGD",
        "detail": f"severity_tier={severity_tier!r} carries a frozen LGD of {lgd:.4f}, applied "
                  f"multiplicatively to every ECL figure above",
    })
    return reasons


if __name__ == "__main__":
    _bundle = load_bundle()
    print(compute_ecl(0.10, "Moderate Severity", _bundle))
