# AMEX Enterprise Credit Risk Platform -- Dynamic/Behavioral Credit Scoring API.
# Auto-generated by 40_dynamic_behavioral_scoring_validation_deployment.ipynb.
# Scores a customer using ONLY their most recent 3 chronological statements -- see /model-info.
# Run with:
#     uvicorn dynamic_behavioral_service:app --host 0.0.0.0 --port 8006
import os
from pathlib import Path
from typing import Optional

import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, create_model

# Self-contained default: this repo's own models/ folder (sibling of src/), matching Problem 5's
# early_default_service.py pattern -- no local machine path needed. Override with
# AMEX_DBS_MODELS_DIR to point elsewhere in production.
MODELS_DIR = Path(os.environ.get("AMEX_DBS_MODELS_DIR", str(Path(__file__).resolve().parent.parent / "models")))

preprocessing_artifacts = joblib.load(MODELS_DIR / "preprocessing_artifacts.joblib")
feature_medians = preprocessing_artifacts["feature_medians"]
all_feature_cols = preprocessing_artifacts["all_feature_cols"]
TRAILING_WINDOW_W = preprocessing_artifacts["w"]
model = joblib.load(MODELS_DIR / preprocessing_artifacts["model_filename"])

_schema_fields = {_c: (Optional[float], None) for _c in all_feature_cols}
CustomerFeatures = create_model("CustomerFeatures", **_schema_fields)


class DynamicBehavioralResponse(BaseModel):
    customer_id: Optional[str] = None
    predicted_pd: float
    trailing_window_w: int
    meets_kpi_target: bool = True


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Dynamic/Behavioral Credit Scoring API",
    description="Re-scores default risk using only a customer's most recent 3 chronological "
                "statements -- a RECENCY score, complementary to Problem 1's full-history champion, not a "
                "replacement for it. See /model-info for the real validation metrics behind this model.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok", "trailing_window_w": TRAILING_WINDOW_W}


@app.get("/model-info")
def model_info():
    return {
        "trailing_window_w": TRAILING_WINDOW_W,
        "meets_kpi_target": True,
        "holdout_auc": 0.9540951936013714,
        "holdout_pr_auc": 0.8795936207205873,
        "holdout_amex_metric": 0.7609196295979701,
        "auc_retention_pct_of_full_history": 99.17420639828329,
        "recommended_for_production": True,
    }


@app.post("/score", response_model=DynamicBehavioralResponse)
def score(features: CustomerFeatures, customer_id: Optional[str] = None):
    row = features.dict() if hasattr(features, "dict") else features.model_dump()
    x = np.zeros((1, len(all_feature_cols)), dtype=np.float32)
    for i, col in enumerate(all_feature_cols):
        val = row.get(col)
        if val is None or (isinstance(val, float) and np.isnan(val)):
            val = feature_medians[col]
        x[0, i] = val
    try:
        pd_score = float(model.predict_proba(x)[:, 1][0])
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    return DynamicBehavioralResponse(customer_id=customer_id, predicted_pd=pd_score, trailing_window_w=TRAILING_WINDOW_W)
