"""Population Stability Index (bin-share) helper -- extracted verbatim from
Problem1_Credit_Scoring_PD_Prediction/src/monitoring/monitoring_job.py
(itself generated by 12_monitoring.ipynb).

See that module's own docstring/comment for the known limitation this
carries forward unchanged: this reports the new-window bin share against
fixed train-side bin edges, not a full two-sided PSI, since the notebook's
monitoring_baseline.json does not (yet) persist per-bin train counts.
"""
from __future__ import annotations

from typing import Optional

import numpy as np


def psi_bin_share(train_edges, window_col) -> Optional[list]:
    """Bin-share of `window_col` against fixed `train_edges` (quantile bin
    edges computed at training time). Returns None if fewer than 3 edges
    were provided (not enough to form a bin)."""
    edges = np.array(train_edges)
    if len(edges) < 3:
        return None
    window_counts, _ = np.histogram(window_col, bins=edges)
    window_pct = np.clip(window_counts / max(window_counts.sum(), 1), 1e-6, None)
    return window_pct.tolist()
