"""Generic band/threshold assignment -- generalized from `assign_tier()` in
Problem2_Risk_Tier_Classification/src/fastapi_service/risk_tier_service.py
(itself generated by 22_risk_tier_deployment.ipynb).

The original `assign_tier(pd_value)` is specific to Problem 2's
risk_tier_policy.json shape (a list of dicts with `pd_lower`/`pd_upper`/
`risk_tier`/`tier_order` keys). This version takes the key names as
parameters so the same band-assignment logic can be reused for any future
threshold-bucketed policy in this platform (e.g. a severity-tier policy
shaped like Problem 4's LGD tiers) without re-deriving the same
half-open-interval-with-fallback logic again.
"""
from __future__ import annotations

from typing import Any, Dict, List


def assign_band(
    value: float,
    bands: List[Dict[str, Any]],
    lower_key: str,
    upper_key: str,
    label_key: str,
    order_key: str,
) -> Any:
    """Return the label of the band whose [lower, upper) half-open interval
    contains `value`, after sorting `bands` by `order_key`.

    Matches the original `assign_tier()` behavior exactly, including its
    fallback: if `value` doesn't fall inside any band (e.g. it's below the
    lowest band's lower bound, which can happen if a caller passes a value
    outside the policy's expected [0, 1) range), the LAST band (highest
    order) is returned rather than raising -- this is the original
    implementation's real behavior, carried forward unchanged here rather
    than "fixed", since Problem 2's service already depends on this exact
    fallback.
    """
    sorted_bands = sorted(bands, key=lambda b: b[order_key])
    for band in sorted_bands:
        if band[lower_key] <= value < band[upper_key]:
            return band[label_key]
    return sorted_bands[-1][label_key]
