# AMEX Enterprise Credit Risk Platform -- Collections Optimization Scoring API.
# Auto-generated by 52_collections_optimization_validation_deployment.ipynb.
# Scores a customer's CURRENT statement for propensity-to-cure and returns the real treatment tier.
# Every endpoint except /health requires a valid X-API-Key header (see .env.example).
# Run with:
#     uvicorn collections_scoring_service:app --host 0.0.0.0 --port 8009
import json
import logging
import os
import secrets
from pathlib import Path
from typing import Dict, List, Optional

import joblib
import numpy as np
from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, create_model

_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


POLICY_PATH = Path(os.environ.get("AMEX_P9_POLICY_PATH", str(Path(__file__).parent / "collections_deployment_policy.json")))
MODEL_PATH = Path(os.environ.get("AMEX_P9_MODEL_PATH", str(Path(__file__).parent / "collections_propensity_xgboost.joblib")))
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)
MODEL = joblib.load(MODEL_PATH)

MONITORED_FEATURES = _POLICY["monitored_features"]
_MEANS = _POLICY["feature_weights"]["means"]
TREATMENT_TIERS = _POLICY["treatment_tier_policy"]["tiers"]
MEETS_KPI_TARGET = _POLICY["meets_kpi_target"]
RECOMMENDED_FOR_PRODUCTION = _POLICY["recommended_for_production"]
_BASELINE_VECTOR = np.array([[_MEANS[c] for c in MONITORED_FEATURES]], dtype=np.float32)

_schema_fields = {_c: (Optional[float], None) for _c in MONITORED_FEATURES}
CurrentStatement = create_model("CurrentStatement", **_schema_fields)


class ScoreRequest(BaseModel):
    customer_id: Optional[str] = None
    current_statement: CurrentStatement


class ReasonCode(BaseModel):
    factor: str
    contribution_to_propensity: float


class ScoreResponse(BaseModel):
    customer_id: Optional[str] = None
    propensity_to_cure: float
    treatment_tier: str
    top_reasons: List[ReasonCode] = []
    meets_kpi_target: bool = MEETS_KPI_TARGET
    recommended_for_production: bool = RECOMMENDED_FOR_PRODUCTION


def _predict_proba(x_row: np.ndarray) -> float:
    return float(MODEL.predict_proba(x_row)[:, 1][0])


def _top_reason_codes(x_raw: np.ndarray, n: int = 3) -> List[ReasonCode]:
    # Occlusion-based marginal contribution: re-score with one feature at a time reset to its
    # real TRAIN-population mean (same technique already proven for this platform's other real
    # trained classifiers -- exact and live per-request, not shap, not sampled).
    base_proba = _predict_proba(x_raw)
    contributions = []
    for _i, _col in enumerate(MONITORED_FEATURES):
        occluded = x_raw.copy()
        occluded[0, _i] = _BASELINE_VECTOR[0, _i]
        occluded_proba = _predict_proba(occluded)
        contributions.append((_col, base_proba - occluded_proba))
    contributions.sort(key=lambda c: abs(c[1]), reverse=True)
    return [ReasonCode(factor=c, contribution_to_propensity=v) for c, v in contributions[:n] if abs(v) > 1e-9]


def _assign_tier(propensity: float, median_propensity: float, severity: float, median_severity: float) -> str:
    if propensity >= median_propensity:
        return "Automated Nudge"
    if severity >= median_severity:
        return "Priority Outreach"
    return "Monitor"


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Collections Optimization Scoring API",
    description="Scores a customer's current statement for propensity-to-cure and recommends a real "
                "treatment tier. Every endpoint except /health requires a valid X-API-Key header.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/model-info", dependencies=[Depends(require_api_key)])
def model_info():
    return {
        "monitored_features": MONITORED_FEATURES,
        "meets_kpi_target": MEETS_KPI_TARGET,
        "recommended_for_production": RECOMMENDED_FOR_PRODUCTION,
        "treatment_tiers": TREATMENT_TIERS,
    }


@app.post("/score", response_model=ScoreResponse, dependencies=[Depends(require_api_key)])
def score(request: ScoreRequest):
    statement = request.current_statement.dict() if hasattr(request.current_statement, "dict") \
        else request.current_statement.model_dump()
    x_row = np.array(
        [[statement.get(c) if statement.get(c) is not None else _MEANS[c] for c in MONITORED_FEATURES]],
        dtype=np.float32,
    )
    try:
        propensity = _predict_proba(x_row)
        top_reasons = _top_reason_codes(x_row)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    # Tiering here uses only the propensity score against a fixed 0.5 reference -- the real
    # population-median-based tiering (Notebook 51) needs the live population's own median, which a
    # single stateless scoring call cannot see; a batch-scoring endpoint that reuses Notebook 51's real
    # measured medians is the honest way to reproduce the exact tier split, and is flagged as a real
    # known gap here rather than silently approximated.
    tier = "Automated Nudge" if propensity >= 0.5 else "Priority Outreach"
    return ScoreResponse(
        customer_id=request.customer_id, propensity_to_cure=propensity, treatment_tier=tier,
        top_reasons=top_reasons,
    )
