# AMEX Enterprise Credit Risk Platform -- Real-Time Risk-Tier Scoring API.
# Auto-generated by 22_risk_tier_deployment.ipynb. Run with:
#     uvicorn risk_tier_service:app --host 0.0.0.0 --port 8001
# AMEX_PROJECT_ROOT (required, see .env.example) must point at your own local
# AMEX_Enterprise_Credit_Risk_Platform folder -- there is no repo-relative
# default here because the real multi-GB champion model is not committed to
# this public repo (see models/README.md). API_KEY (see .env.example) gates
# every endpoint below except /health.
import logging
import os
import json
import secrets
from pathlib import Path
from typing import List, Optional

import joblib
import numpy as np
from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, create_model

_env_root = os.environ.get("AMEX_PROJECT_ROOT")
if not _env_root:
    raise RuntimeError(
        "AMEX_PROJECT_ROOT is not set. This service needs the path to your own local "
        "AMEX_Enterprise_Credit_Risk_Platform folder (containing artifacts/project_config.json) "
        "-- see this problem's own README.md and .env.example. Fixed 2026-08-25: this used to "
        "default to the author's own local Windows path, the same privacy-leak bug class already "
        "found and fixed elsewhere in this platform (see CHANGELOG.md)."
    )
PROJECT_ROOT = Path(_env_root)
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"

# ---------------------------------------------------------------------------
# Authentication -- real, enforced on every endpoint below except /health.
# Duplicated verbatim across all 8 platform services (not imported from
# shared/) so each service stays self-contained for its own Docker build
# context, matching the self-contained-policy-copy pattern already used
# elsewhere in this repo. Set API_KEY in your environment before deploying
# anywhere reachable by anyone but you -- the fallback below is published
# publicly in this file and must never be treated as a real secret.
# ---------------------------------------------------------------------------
_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented

with open(ARTIFACTS_DIR / "project_config.json", "r", encoding="utf-8") as f:
    _config = json.load(f)
_pillar_dirs = {k: Path(v) for k, v in _config["pillar_dirs"].items()}
_model_dev_dir = _pillar_dirs["model_development"]
_models_subdir = _model_dev_dir / "models"
_risk_tier_policy_dir = _pillar_dirs["risk_tier_policy"]

with open(ARTIFACTS_DIR / "notebook_05_summary.json", "r", encoding="utf-8") as f:
    _nb05_summary = json.load(f)
CHAMPION_NAME = _nb05_summary["champion_model"]
CHAMPION_METRICS = _nb05_summary["champion_metrics"]

with open(_risk_tier_policy_dir / "risk_tier_policy.json", "r", encoding="utf-8") as f:
    RISK_TIER_POLICY = json.load(f)
_BR_THRESHOLDS = sorted(RISK_TIER_POLICY["bucketing_methods"]["business_rule"]["pd_thresholds"],
                        key=lambda b: b["tier_order"])


def assign_tier(pd_value):
    for band in _BR_THRESHOLDS:
        if band["pd_lower"] <= pd_value < band["pd_upper"]:
            return band["risk_tier"]
    return _BR_THRESHOLDS[-1]["risk_tier"]


champion_model = joblib.load(_models_subdir / (CHAMPION_NAME + ".joblib"))
preprocessing_artifacts = joblib.load(_models_subdir / "preprocessing_artifacts.joblib")
label_encoders = preprocessing_artifacts["label_encoders"]
feature_medians = preprocessing_artifacts["feature_medians"]
scaler = preprocessing_artifacts["scaler"]
all_feature_cols = preprocessing_artifacts["all_feature_cols"]
categorical_encode_cols = preprocessing_artifacts["categorical_encode_cols"]
numeric_feature_cols = preprocessing_artifacts["numeric_feature_cols"]
champion_uses_scaled = CHAMPION_NAME == "logistic_regression"

_schema_fields = {}
for _c in numeric_feature_cols:
    _schema_fields[_c] = (Optional[float], None)
for _c in categorical_encode_cols:
    _schema_fields[_c] = (Optional[str], None)
CustomerFeatures = create_model("CustomerFeatures", **_schema_fields)


class ReasonCode(BaseModel):
    factor: str
    contribution_to_predicted_pd: float


class RiskTierResponse(BaseModel):
    customer_id: Optional[str] = None
    predicted_pd: float
    risk_tier: str
    tier_method: str
    champion_model: str
    top_reasons: List[ReasonCode] = []


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Risk Tier Scoring API",
    description="Real-time PD scoring plus policy-based risk-tier classification (Notebook 19's real policy).",
    version="1.0.0",
)


def _predict_pd(x_matrix):
    xx = x_matrix.copy()
    if champion_uses_scaled:
        xx = (xx - scaler["mean"]) / scaler["std"]
    return float(champion_model.predict_proba(xx)[:, 1][0])


def _baseline_vector():
    baseline = np.zeros((1, len(all_feature_cols)), dtype=np.float32)
    for i, col in enumerate(all_feature_cols):
        if col in categorical_encode_cols:
            classes = label_encoders[col]["classes"]
            mapping = {cat: idx for idx, cat in enumerate(classes)}
            baseline[0, i] = mapping.get("__missing__", -1)
        else:
            baseline[0, i] = feature_medians[col]
    return baseline


def _top_reason_codes(x_raw, n=3):
    """Same real, exact marginal-contribution technique as Problem 1's PD service (see that
    file's docstring) -- applied here to the same champion model, so a customer's risk-tier
    placement carries the same real, per-request explanation its underlying PD does."""
    base_pred = _predict_pd(x_raw)
    baseline = _baseline_vector()
    impacts = []
    for i, col in enumerate(all_feature_cols):
        if x_raw[0, i] == baseline[0, i]:
            continue
        occluded = x_raw.copy()
        occluded[0, i] = baseline[0, i]
        impacts.append(ReasonCode(
            factor=col,
            contribution_to_predicted_pd=base_pred - _predict_pd(occluded),
        ))
    impacts.sort(key=lambda r: abs(r.contribution_to_predicted_pd), reverse=True)
    return impacts[:n]


@app.get("/health")
def health():
    return {"status": "ok", "champion_model": CHAMPION_NAME}


@app.get("/policy-info", dependencies=[Depends(require_api_key)])
def policy_info():
    return {
        "n_tiers": RISK_TIER_POLICY["n_tiers"],
        "tier_order": RISK_TIER_POLICY["tier_order"],
        "primary_method": RISK_TIER_POLICY["primary_method"],
        "business_rule_thresholds": _BR_THRESHOLDS,
    }


@app.post("/risk-tier", response_model=RiskTierResponse, dependencies=[Depends(require_api_key)])
def risk_tier(features: CustomerFeatures, customer_id: Optional[str] = None):
    row = features.dict() if hasattr(features, "dict") else features.model_dump()
    x = np.zeros((1, len(all_feature_cols)), dtype=np.float32)
    for i, col in enumerate(all_feature_cols):
        val = row.get(col)
        if col in categorical_encode_cols:
            classes = label_encoders[col]["classes"]
            mapping = {cat: idx for idx, cat in enumerate(classes)}
            x[0, i] = mapping.get(val if val is not None else "__missing__", -1)
        else:
            if val is None or (isinstance(val, float) and np.isnan(val)):
                val = feature_medians[col]
            x[0, i] = val
    try:
        pd_score = _predict_pd(x)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    tier = assign_tier(pd_score)
    reasons = _top_reason_codes(x)
    return RiskTierResponse(customer_id=customer_id, predicted_pd=pd_score, risk_tier=tier,
                             tier_method="business_rule", champion_model=CHAMPION_NAME,
                             top_reasons=reasons)
