# AMEX Enterprise Credit Risk Platform -- Early Payment Default Scoring API.
# Auto-generated by 36_early_payment_default_validation_deployment.ipynb.
# Scores a customer using ONLY their first 3 chronological statements -- see /model-info.
# Run with:
#     uvicorn early_default_service:app --host 0.0.0.0 --port 8002
import os
from pathlib import Path
from typing import Optional

import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, create_model

# Self-contained default: the repo's own models/ folder (real trained artifacts ship there,
# see models/README.md). Override with AMEX_EPD_MODELS_DIR to point elsewhere (e.g. a separate
# model registry volume in production). Never hardcode a local machine's path here -- this file
# is published publicly.
MODELS_DIR = Path(os.environ.get("AMEX_EPD_MODELS_DIR", str(Path(__file__).resolve().parents[1] / "models")))

preprocessing_artifacts = joblib.load(MODELS_DIR / "preprocessing_artifacts.joblib")
label_encoders = preprocessing_artifacts["label_encoders"]
feature_medians = preprocessing_artifacts["feature_medians"]
all_feature_cols = preprocessing_artifacts["all_feature_cols"]
categorical_encode_cols = preprocessing_artifacts["categorical_encode_cols"]
numeric_feature_cols = preprocessing_artifacts["numeric_feature_cols"]
EARLY_WINDOW_K = preprocessing_artifacts["k"]
model = joblib.load(MODELS_DIR / preprocessing_artifacts["model_filename"])

_schema_fields = {}
for _c in numeric_feature_cols:
    _schema_fields[_c] = (Optional[float], None)
for _c in categorical_encode_cols:
    _schema_fields[_c] = (Optional[str], None)
CustomerFeatures = create_model("CustomerFeatures", **_schema_fields)


class EarlyDefaultResponse(BaseModel):
    customer_id: Optional[str] = None
    predicted_pd: float
    early_window_k: int
    meets_kpi_target: bool = True


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Early Payment Default Scoring API",
    description="Scores default risk using only a customer's first 3 chronological "
                "statements. See /model-info for the real validation metrics behind this model.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok", "early_window_k": EARLY_WINDOW_K}


@app.get("/model-info")
def model_info():
    return {
        "early_window_k": EARLY_WINDOW_K,
        "meets_kpi_target": True,
        "holdout_auc": 0.9265274920113401,
        "holdout_amex_metric": 0.65550906419563,
        "auc_retention_pct_of_full_history": 96.30865907580267,
        "recommended_for_production": True,
    }


@app.post("/score", response_model=EarlyDefaultResponse)
def score(features: CustomerFeatures, customer_id: Optional[str] = None):
    row = features.model_dump() if hasattr(features, "model_dump") else features.dict()
    x = np.zeros((1, len(all_feature_cols)), dtype=np.float32)
    for i, col in enumerate(all_feature_cols):
        val = row.get(col)
        if col in categorical_encode_cols:
            classes = label_encoders[col]["classes"]
            mapping = {cat: idx for idx, cat in enumerate(classes)}
            x[0, i] = mapping.get(val if val is not None else "__missing__", -1)
        else:
            if val is None or (isinstance(val, float) and np.isnan(val)):
                val = feature_medians[col]
            x[0, i] = val
    try:
        pd_score = float(model.predict_proba(x)[:, 1][0])
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    return EarlyDefaultResponse(customer_id=customer_id, predicted_pd=pd_score, early_window_k=EARLY_WINDOW_K)
