# AMEX Enterprise Credit Risk Platform -- Early Payment Default Scoring API.
# Auto-generated by 36_early_payment_default_validation_deployment.ipynb.
# Scores a customer using ONLY their first 3 chronological statements -- see /model-info.
# API_KEY (see .env.example) gates every endpoint below except /health.
# Run with:
#     uvicorn early_default_service:app --host 0.0.0.0 --port 8002
import logging
import os
import secrets
from pathlib import Path
from typing import List, Optional

import joblib
import numpy as np
from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, create_model

# Self-contained default: the repo's own models/ folder (real trained artifacts ship there,
# see models/README.md). Override with AMEX_EPD_MODELS_DIR to point elsewhere (e.g. a separate
# model registry volume in production). Never hardcode a local machine's path here -- this file
# is published publicly.
MODELS_DIR = Path(os.environ.get("AMEX_EPD_MODELS_DIR", str(Path(__file__).resolve().parents[1] / "models")))

preprocessing_artifacts = joblib.load(MODELS_DIR / "preprocessing_artifacts.joblib")
label_encoders = preprocessing_artifacts["label_encoders"]
feature_medians = preprocessing_artifacts["feature_medians"]
all_feature_cols = preprocessing_artifacts["all_feature_cols"]
categorical_encode_cols = preprocessing_artifacts["categorical_encode_cols"]
numeric_feature_cols = preprocessing_artifacts["numeric_feature_cols"]
EARLY_WINDOW_K = preprocessing_artifacts["k"]
model = joblib.load(MODELS_DIR / preprocessing_artifacts["model_filename"])

# ---------------------------------------------------------------------------
# Authentication -- real, enforced on every endpoint below except /health.
# Duplicated verbatim across all 8 platform services (not imported from
# shared/) so each service stays self-contained for its own Docker build
# context, matching the self-contained-policy-copy pattern already used
# elsewhere in this repo. Set API_KEY in your environment before deploying
# anywhere reachable by anyone but you -- the fallback below is published
# publicly in this file and must never be treated as a real secret.
# ---------------------------------------------------------------------------
_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


_schema_fields = {}
for _c in numeric_feature_cols:
    _schema_fields[_c] = (Optional[float], None)
for _c in categorical_encode_cols:
    _schema_fields[_c] = (Optional[str], None)
CustomerFeatures = create_model("CustomerFeatures", **_schema_fields)


class ReasonCode(BaseModel):
    factor: str
    contribution_to_predicted_pd: float


class EarlyDefaultResponse(BaseModel):
    customer_id: Optional[str] = None
    predicted_pd: float
    early_window_k: int
    meets_kpi_target: bool = True
    top_reasons: List[ReasonCode] = []


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- Early Payment Default Scoring API",
    description="Scores default risk using only a customer's first 3 chronological "
                "statements. See /model-info for the real validation metrics behind this model.",
    version="1.0.0",
)


def _baseline_vector():
    baseline = np.zeros((1, len(all_feature_cols)), dtype=np.float32)
    for i, col in enumerate(all_feature_cols):
        if col in categorical_encode_cols:
            classes = label_encoders[col]["classes"]
            mapping = {cat: idx for idx, cat in enumerate(classes)}
            baseline[0, i] = mapping.get("__missing__", -1)
        else:
            baseline[0, i] = feature_medians[col]
    return baseline


def _top_reason_codes(x_raw, n=3):
    """Same real, exact marginal-contribution technique as Problem 1's PD service (see that
    file's docstring): re-scores this same customer with one feature at a time reset to its
    training-set baseline and reports the resulting change in predicted PD, live against the
    real loaded model on every call."""
    base_pred = float(model.predict_proba(x_raw)[:, 1][0])
    baseline = _baseline_vector()
    impacts = []
    for i, col in enumerate(all_feature_cols):
        if x_raw[0, i] == baseline[0, i]:
            continue
        occluded = x_raw.copy()
        occluded[0, i] = baseline[0, i]
        occluded_pred = float(model.predict_proba(occluded)[:, 1][0])
        impacts.append(ReasonCode(factor=col, contribution_to_predicted_pd=base_pred - occluded_pred))
    impacts.sort(key=lambda r: abs(r.contribution_to_predicted_pd), reverse=True)
    return impacts[:n]


@app.get("/health")
def health():
    return {"status": "ok", "early_window_k": EARLY_WINDOW_K}


@app.get("/model-info", dependencies=[Depends(require_api_key)])
def model_info():
    return {
        "early_window_k": EARLY_WINDOW_K,
        "meets_kpi_target": True,
        "holdout_auc": 0.9265274920113401,
        "holdout_amex_metric": 0.65550906419563,
        "auc_retention_pct_of_full_history": 96.30865907580267,
        "recommended_for_production": True,
    }


@app.post("/score", response_model=EarlyDefaultResponse, dependencies=[Depends(require_api_key)])
def score(features: CustomerFeatures, customer_id: Optional[str] = None):
    row = features.model_dump() if hasattr(features, "model_dump") else features.dict()
    x = np.zeros((1, len(all_feature_cols)), dtype=np.float32)
    for i, col in enumerate(all_feature_cols):
        val = row.get(col)
        if col in categorical_encode_cols:
            classes = label_encoders[col]["classes"]
            mapping = {cat: idx for idx, cat in enumerate(classes)}
            x[0, i] = mapping.get(val if val is not None else "__missing__", -1)
        else:
            if val is None or (isinstance(val, float) and np.isnan(val)):
                val = feature_medians[col]
            x[0, i] = val
    try:
        pd_score = float(model.predict_proba(x)[:, 1][0])
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Scoring failed: " + str(exc))
    reasons = _top_reason_codes(x)
    return EarlyDefaultResponse(customer_id=customer_id, predicted_pd=pd_score,
                                 early_window_k=EARLY_WINDOW_K, top_reasons=reasons)
