# AMEX Enterprise Credit Risk Platform -- 360 Degree Customer Intelligence Lookup API.
# Auto-generated by 64_customer_intelligence_validation_deployment.ipynb.
# Serves each customer's real precomputed UNIFIED_RISK_SCORE / UNIFIED_RISK_GRADE profile, composed
# from Problem 1 (static PD), Problem 6 (dynamic PD), Problem 9 (propensity-to-cure, collections-
# eligible customers only), and Problem 10 (risk-level/trend/action worklist).
# Every endpoint except /health requires a valid X-API-Key header (see .env.example).
# Run with:
#     uvicorn customer_intelligence_lookup_service:app --host 0.0.0.0 --port 8012
import json
import logging
import os
import secrets
from pathlib import Path
from typing import List, Optional

import polars as pl
from fastapi import Depends, FastAPI, HTTPException, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel

_auth_logger = logging.getLogger(__name__ + ".auth")
_DEV_DEFAULT_API_KEY = "dev-only-CHANGE-ME-before-deploying"
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _configured_api_key() -> str:
    key = os.environ.get("API_KEY")
    if not key:
        _auth_logger.warning(
            "API_KEY is not set -- falling back to the published dev-only default. Set API_KEY "
            "before deploying this service anywhere reachable by anyone but you."
        )
        return _DEV_DEFAULT_API_KEY
    return key


def require_api_key(presented: str = Security(_api_key_header)) -> str:
    expected = _configured_api_key()
    if not presented or not secrets.compare_digest(presented, expected):
        raise HTTPException(status_code=401, detail="Missing or invalid X-API-Key header.")
    return presented


POLICY_PATH = Path(os.environ.get("AMEX_P12_POLICY_PATH", str(Path(__file__).parent / "customer_intelligence_deployment_policy.json")))
PROFILE_PATH = Path(os.environ.get("AMEX_P12_PROFILE_PATH", str(Path(__file__).parent.parent / "data" / "data/unified_customer_profile.parquet")))
with open(POLICY_PATH, "r", encoding="utf-8") as _f:
    _POLICY = json.load(_f)

UNIFIED_RISK_GRADE_NAMES = _POLICY["unified_risk_grade_names"]
UNIFIED_SCORE_WEIGHTS = _POLICY["unified_score_weights"]
GRADE_CUT_LOW = _POLICY["unified_grade_cut_low"]
GRADE_CUT_HIGH = _POLICY["unified_grade_cut_high"]
RECOMMENDED_FOR_PRODUCTION = _POLICY["recommended_for_production"]

_PROFILE_DF = pl.read_parquet(PROFILE_PATH)
_PROFILE_INDEX = {row["customer_ID"]: row for row in _PROFILE_DF.iter_rows(named=True)}


class ProfileResponse(BaseModel):
    customer_id: str
    static_pd: float
    dynamic_pd: float
    pd_trend: float
    risk_level: str
    trend_segment: str
    credit_line_action: str
    collections_eligible: bool
    propensity_to_cure: Optional[float] = None
    treatment_tier: Optional[str] = None
    unified_risk_score: float
    unified_risk_grade: str
    rationale: str
    reasoning: List[str] = []
    recommended_for_production: bool = RECOMMENDED_FOR_PRODUCTION


app = FastAPI(
    title="AMEX Enterprise Credit Risk Platform -- 360 Degree Customer Intelligence Lookup API",
    description="Serves each real customer's precomputed unified risk profile, composed from four real, "
                "already-validated upstream signals. Every endpoint except /health requires a valid "
                "X-API-Key header.",
    version="1.0.0",
)


@app.get("/health")
def health():
    return {"status": "ok", "profiles_loaded": len(_PROFILE_INDEX)}


@app.get("/policy-info", dependencies=[Depends(require_api_key)])
def policy_info():
    return {
        "unified_risk_grade_names": UNIFIED_RISK_GRADE_NAMES,
        "unified_score_weights": UNIFIED_SCORE_WEIGHTS,
        "unified_grade_cuts": [GRADE_CUT_LOW, GRADE_CUT_HIGH],
        "recommended_for_production": RECOMMENDED_FOR_PRODUCTION,
        "profiles_loaded": len(_PROFILE_INDEX),
    }


@app.get("/profile/{customer_id}", response_model=ProfileResponse, dependencies=[Depends(require_api_key)])
def get_profile(customer_id: str):
    row = _PROFILE_INDEX.get(customer_id)
    if row is None:
        raise HTTPException(status_code=404, detail=f"No unified profile found for customer_id={customer_id!r}.")
    sw = UNIFIED_SCORE_WEIGHTS["static_pd_weight"]
    dw = UNIFIED_SCORE_WEIGHTS["dynamic_pd_weight"]
    cw = UNIFIED_SCORE_WEIGHTS["collections_adjustment_weight"]
    reasoning = [
        f"static_pd={row['STATIC_PD']:.4f} x weight {sw} -> {sw * row['STATIC_PD']:.4f}",
        f"dynamic_pd={row['DYNAMIC_PD']:.4f} x weight {dw} -> {dw * row['DYNAMIC_PD']:.4f}",
    ]
    if row.get("PROPENSITY_TO_CURE") is not None:
        reasoning.append(
            f"propensity_to_cure={row['PROPENSITY_TO_CURE']:.4f} (collections-eligible) x weight {cw} "
            f"-> {cw * (1.0 - row['PROPENSITY_TO_CURE']):.4f} (as 1 - propensity), renormalized"
        )
    else:
        reasoning.append("propensity_to_cure=null (customer is not currently collections-eligible; "
                         "the collections adjustment term is honestly excluded, not imputed)")
    reasoning.append(
        f"unified_risk_score={row['UNIFIED_RISK_SCORE']:.4f} -> {row['UNIFIED_RISK_GRADE']} "
        f"(cuts: <= {GRADE_CUT_LOW:.4f} {UNIFIED_RISK_GRADE_NAMES[0]}, "
        f"<= {GRADE_CUT_HIGH:.4f} {UNIFIED_RISK_GRADE_NAMES[1]}, else {UNIFIED_RISK_GRADE_NAMES[2]})"
    )
    return ProfileResponse(
        customer_id=row["customer_ID"], static_pd=row["STATIC_PD"], dynamic_pd=row["DYNAMIC_PD"],
        pd_trend=row["PD_TREND"], risk_level=row["RISK_LEVEL"], trend_segment=row["TREND_SEGMENT"],
        credit_line_action=row["CREDIT_LINE_ACTION"], collections_eligible=row["COLLECTIONS_ELIGIBLE"],
        propensity_to_cure=row.get("PROPENSITY_TO_CURE"), treatment_tier=row.get("TREATMENT_TIER"),
        unified_risk_score=row["UNIFIED_RISK_SCORE"], unified_risk_grade=row["UNIFIED_RISK_GRADE"],
        rationale=f"Composite of static PD ({sw:.0%}), dynamic PD ({dw:.0%})"
                  + (f", and collections propensity ({cw:.0%})" if row.get("PROPENSITY_TO_CURE") is not None else " (collections term not applicable)") + ".",
        reasoning=reasoning,
    )
